version: '3.8'

services:
  web:
    build: .
    container_name: employee_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - employee_network

  db:
    image: mysql:8.0
    container_name: employee_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - employee_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: employee_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - employee_network

volumes:
  db_data:

networks:
  employee_network:
    driver: bridge